# Generated by Django 6.0.5 on 2026-06-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('body', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('date_released', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(blank=True, default='default_img.jpg', null=True, upload_to='')),
            ],
        ),
    ]
