# Generated by Django 6.0.5 on 2026-06-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mediaType',
        ),
    ]
