version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Sparar databasfilen på din lokala dator så att data inte försvinner
      - ./db.sqlite3:/app/db.sqlite3
